spring:
  application:
    name: sql-ex
  jpa:
    properties:
      hibernate:
        show_sql: true

  liquibase:
    enabled: false

  main:
    banner-mode: off

springdoc:
  paths-to-match: /**
  show-actuator: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'