db:
  datasource:
    database: postgres
    username: postgres
    password: postgres
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

logging:
  config: config/logback-spring-local.xml

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces